### ISSUE TITLE
Create static Location pages

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#103]

**Comment by rkdavidson** [comment]
@jordanwade I think you've started on this already, so assigning to you if that's alright.

**Comment by jordanwade** [comment]
@asleepingpanda since Page Builder was merged can this be accomplished easily using that instead of me copying all the static content over?

Do you have an example of how Page Builder works?

**Comment by drewbarontini** [comment]
Tracked in Jira.
