### ISSUE TITLE
Turn off Group Finder feature flag

### ISSUE THREAD

**Issue by drewbarontini** [christfellowshipchurch/web-app-v2#117]
Reference #116 to set `GROUP_FINDER` to `true` and update `next.config.js`.

We can also remove all the feature flags, too, if we're not going to use it again.

**Comment by jordanwade** [comment]
@drewbarontini is this just to keep track for launch? No further work needs to be done, correct?

**Comment by drewbarontini** [comment]
@jordanwade Correct. This is just so we can do this immediately before launch.
