### ISSUE TITLE
Can't click on certain home-feed cards when signed out

### ISSUE THREAD

**Issue by drewbarontini** [christfellowshipchurch/web-app-v2#119]
![CleanShot 2021-04-27 at 16 48 35@2x](https://user-images.githubusercontent.com/30208/116310789-73769f00-a778-11eb-8528-0e4692253c56.png)

- Given I'm signed out
- And I'm on the home page
- When I click on the "Get Connected" card
- Or I click on the "Foundations of Faith" card
- Then I'm redirected back to the home page

**Comment by jordanwade** [comment]
Looks like this is related to the route stuff @asleepingpanda did recently. There is no pathname for those items and I think that means the content team needs to update those items in Rock with pathnames. @asleepingpanda can you confirm this please? https://github.com/christfellowshipchurch/web-app-v2/blob/a37c1ce4bc6aaf5766066aafc70835e63d232626/utils/getUrlFromRelatedNode.js#L11
![image](https://user-images.githubusercontent.com/2528817/116593975-52808c00-a8e7-11eb-95f4-6e1e416dcf25.png)

**Comment by drewbarontini** [comment]
@asleepingpanda Feel free to pull this one into Jira if you want to track this there instead of here 👍

**Comment by jordanwade** [comment]
@asleepingpanda closing since you guys are working on this stuff as stated in our meeting today
