### ISSUE TITLE
Require authentication for /groups

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#130]
IMO this page doesn't have any value right now. Should we hide the **Groups** link from the navigation unless you're logged in? Update the language to say "Log in to see your groups?" Etc?

![image](https://user-images.githubusercontent.com/1812955/116619667-c1251000-a90e-11eb-9a31-e3d098beae0c.png)

**Comment by drewbarontini** [comment]
I agree. Hide it. We can add a nice callout to the Group Finder once it's live.

**Comment by rkdavidson** [comment]
Closing since @asleepingpanda has some changes expected around Group Finder and it may need to live at /groups instead.
