### ISSUE TITLE
Use appropriate dev/prod Chat app credentials

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#135]
For non-production environments, the development app credentials should be used for Stream Chat.
For production, we should use the production app credentials.

**Comment by rkdavidson** [comment]
Hey @asleepingpanda , can I assign this over to you? I think most of the configuration settings for this are either local environment variables or configured in CI/CD somewhere.

I have the dev/prod credentials in a consolidated, simple note — can send it to you via Slack or somewhere more secure.

**Comment by asleepingpanda** [comment]
@rkdavidson gonna close this issue, too, since this is more of an internal processes kind of thing. I have your note saved and will make sure to document in Confluence which values should be used when. From there, it's really just making sure that our internal dev team is following protocol.
