### ISSUE TITLE
Support showing video player for content blocks

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#138]
Sync up with @asleepingpanda for further context.

**Comment by asleepingpanda** [comment]
@rkdavidson Content Block is a UI element that is used by the Content Block Feature. It's essentially a really condensed Content Single. 

An image and/or video get displayed with text content underneath, above, left or right of the media.

Currently, there is already support for the Image so show, but we need the UI element to also support playing Videos inline.

Check out `/get-connected` for an example of a bunch of different Content Blocks in a real-world example.
