### ISSUE TITLE
On first load, the /connect screen fails. Subsequent loads pull data in

### ISSUE THREAD

**Issue by asleepingpanda** [christfellowshipchurch/web-app-v2#155]
## To Replicate:
Log out of the website
Reload the page
Log in
Navigate to the /connect page using the Avatar in the Header
PAGE FAILS TO LOAD
Reload page 1/2 times
PAGE SUCCESSFULLY LOADS

**Comment by jordanwade** [comment]
Could not reproduce...more info needed. Loom, screenshots, etc.

**Comment by asleepingpanda** [comment]
@dzwood please provide some loom recordings/reproduction steps

**Comment by dzwood** [comment]
@jordanwade I was able to recreate the bug when opening the web app in incognito. I sign in and then click on the Profile photo to go to `/connect`. It seems to return some kind of `null` value for cards, after I refresh it normally loads the page fine.

https://www.loom.com/share/2a8ba83c89dd4d39b0785dc4a3a19205

**Comment by rkdavidson** [comment]
Possibly related:

<img width="1920" alt="Screen Shot 2021-05-06 at 2 21 35 PM" src="https://user-images.githubusercontent.com/1812955/117347002-7fe4b100-ae76-11eb-96b7-4b74427d2721.png">

**Comment by asleepingpanda** [comment]
So just like a default value is missing somewhere that should be an empty array
