### ISSUE TITLE
Duplicate results in group finder search

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#209]
![image](https://user-images.githubusercontent.com/1812955/119365920-6fa64180-bc7e-11eb-9f8b-97a692e43e1a.png)

**Comment by jordanwade** [comment]
@rkdavidson are you sure that these aren't all in Rock? The data isn't identical and kind of seems like Sylvia makes a lot of groups. Or are you seeing this with another group?
 
![image](https://user-images.githubusercontent.com/2528817/119404657-bb201600-bca5-11eb-8d64-9eed4757eef5.png)

![image](https://user-images.githubusercontent.com/2528817/119404856-063a2900-bca6-11eb-9074-15b8e17a079e.png)
![image](https://user-images.githubusercontent.com/2528817/119404874-0e926400-bca6-11eb-9e86-838e7a562b3c.png)
![image](https://user-images.githubusercontent.com/2528817/119404978-2f5ab980-bca6-11eb-9fee-07fac7c1dc90.png)
![image](https://user-images.githubusercontent.com/2528817/119405013-3b467b80-bca6-11eb-86a0-a458ca17a972.png)

**Comment by jordanwade** [comment]
Here is another example that looks like duplicate results, but it is just that this Tennis group has three different dates they meet...The Groups team could probably combine entries like this and just have a custom schedule. 🤷‍♂️ 
![image](https://user-images.githubusercontent.com/2528817/119405557-0e469880-bca7-11eb-9faa-1829c467756a.png)

**Comment by rkdavidson** [comment]
@jordanwade Good call, yeah I definitely skimmed too briefly at first and thought all 3 of those Sylvia groups were the same.
There was definitely some duplicate data though — was seeing it in the Apollo client code, but not in the graphql side.
I _suspect_ it's edge casey and not 100% sure how to reproduce it, so I have the code that zippers in new pages of results quickly de-dupe all groups to prevent it 🤞 .

The fix is in #211 .
Thanks for helping take a look, I haven't seen this much so I'm hopeful it's a development and/or re-indexing artifact.
