### ISSUE TITLE
Refine ui-kit Button hover states

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#52]
( Feedback from Caleb )

Button hover states are very high contrast, going from primary blue to white-on-black.

Explore opportunities to soften this transition and overall button pseudo states.

**Comment by jordanwade** [comment]
Closing since this is fixed
![image](https://user-images.githubusercontent.com/2528817/118304323-26026d80-b4ac-11eb-90e5-6f7abd0840de.png)
