### ISSUE TITLE
Remove hard-coded `groupId` in Group Finder Connect flow

### ISSUE THREAD

**Issue by rkdavidson** [christfellowshipchurch/web-app-v2#54]
👀  👉  https://github.com/christfellowshipchurch/web-app-v2/blob/main/components/Modals/ConnectModal/ConnectForm.js#L17

**Comment by rkdavidson** [comment]
Hey @jordanwade, this is a "remove a safety switch" task, yeah?
I.e. after this is merged, the Contact workflow will actually work and request to join groups?

**Comment by jordanwade** [comment]
@rkdavidson yes, once we change that to `props.groupId` the contact workflow will actually work to contact the correct leader.

**Comment by rkdavidson** [comment]
What're your thoughts as far as timing for this change?
I'm a bit torn. It may make sense to knock it out now while it's on our mind, but we'll have to communicate to CF that the button will be live/functional even though the feature hasn't been released yet.

**Comment by jordanwade** [comment]
I feel ya, but I'd hold off a little bit longer. I'm sure there is a lot more testing that is going to happen on that stuff before launch.
